---
name: chatgpt
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  speech_to_text: ^6.5.1
  mic_stream: ^0.7.1+2
  iconsax: ^0.0.8
  flutter_spinkit: ^5.1.0
  chat_gpt_flutter: ^1.0.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  flutter_bloc: ^8.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
      - asset: assets/fonts/Nunito/static/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
        weight: 400
  assets:
    - assets/
